# Generated by Django 5.2.1 on 2025-05-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_table',
            new_name='MenuTable',
        ),
    ]
