# Generated by Django 5.2.1 on 2025-05-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_menu_table_menutable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='Menu',
        ),
    ]
